name: Build and publish package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release:
        description: Release package
        type: boolean
        required: true
        default: false
  
env:
  # set preview mode if not triggered by tags
  release: ${{ startsWith(github.ref, 'refs/tags/') || inputs.release }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
            
    steps:
      - uses: actions/checkout@v3

      - name: Install cross
        run: |
          cargo install cross --git https://github.com/cross-rs/cross.git
          echo "CARGO=cross" >> $GITHUB_ENV

      - name: Build
        run: |
          ${{ env.CARGO }} build --release --locked --target ${{ matrix.target }}
           
      - uses: actions/upload-artifact@v3
        with:
          name: snapshotfs-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/snapshotfs

  publish:
    name: Publish
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3

      - name: Rename and list artifacts
        run: |
          mkdir dist
          for name in snapshotfs-*; do
            mv $name/snapshotfs dist/$name
            rmdir $name
          done
          ls dist

      - name: Cargo release
        if: env.release == 'true'
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}

      - name: GitHub release
        if: env.release == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

